### PR TITLE
Travis CI pipeline

### PR DESCRIPTION
**Pull request by begotxe**
Include the travis pipeline https://travis-ci.com/github/gridscale/gridscale_api_client_python

### CODE REVIEW

**Review by bkircher — COMMENTED** [review]
Looks good to me in general :+1:  but

Maybe it makes it more readable when we put the script contents directly in the YAML file? Like

```yml
    - stage: test_sdist_package
      script:
        - python setup.py sdist bdist_wheel
        - pip install dist/gs_api_client-$(python setup.py --version).tar.gz
    - stage: test_bdist_wheel_package
      script:
        - python setup.py sdist bdist_wheel
        - pip install dist/gs_api_client-$(python setup.py --version).tar.gz
```
instead of
```yml
    - stage: test_sdist_package
      script:
      - ./.travis/build.sh
      - ./.travis/test_sdist_package.sh
    - stage: test_bdist_wheel_package
      script:
      - ./.travis/build.sh
      - ./.travis/test_sdist_wheel_package.sh
```

This way some things might be easier to spot:
-  test_sdist_wheel_package.sh and test_sdist_package.sh are the same. The wheel install test should be `pip install dist/gs_api_client-$(python setup.py --version).linux-x86_64.tar.gz` or something; needs to include platform and arch
- for `test_sdist_package` the build could be simply `python setup.py sdist`
- and for `test_bdist_wheel` the build could be simply `python setup.py bdist`

Side note: is there a `bdist_wheel` command? It fails for me. Maybe you meant `bdist`?

Also maybe we could give the stages more descriptive names.  Thinking of  something like
`test_sdist_package` → `test-install-src`
and
`test_bdist_wheel_package` → `test-install-wheel`
or so. But this can all be done later.

Maybe it also makes sense not to bother with setuptools at all and just do something much simpler like flit ([github.com/takluyver/flit](https://github.com/takluyver/flit))? Do we really need a wheel package? Can this not be just a simple Python-only package? :thinking: 

What ya guys think?

**Comment by begotxe** [comment]
The nice thing of writing each of the steps in a different script is that with `set -ev` it will exit if failure. Is it possible to add something similar in the `.travis.yml` main file? 
Eventhough I competely agree with you, is way cleaner and easier to read if all the commands are on the `.travis.yml` instead of in different scripts
Im trying out your comments and trying to improve it ;)

**Comment by bkircher** [comment]
> The nice thing of writing each of the steps in a different script is that with set -ev it will exit if failure. Is it possible to add something similar in the .travis.yml main file?

Hmm, I think Travis will just abort if one of the commands returns with non-zero exit. But you are absolutely right, there are things that you can do in a Bash scripts that probably won't work in `.travis.yml`. You can for example use pipes in shell scripts (and use -o pipefail) which you probably can't when using `.travis.yml` file.

So if you feel like having Bash scripts, just keep them :slightly_smiling_face:  :+1:

**Comment by begotxe** [comment]
you're right, if the container exits the pipeline stops :) 
Regarding the `bdist_wheel` we need it to build the wheel package. From what I have tested, the command `python setup.py bdist_wheel` works fine.

about keeping the wheel package or not, not sure... I would say that as we already have it we could keep it. Or we can give it a second thought?

I believe the pipeline looks better now :)

**Review by bkircher — APPROVED** [review]

**Pull request merged**
